# ----------------------------------------------------------------------------#
#                                                                             #
#                             Minesweeper config                              #
#                                                                             #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
langFile: "default"

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "TNT"
    # display name of the button
    displayName: "&3Minesweeper"
    # lore of the button
    lore:
    - ""
    - "&1Find all mines"
  gameButtons:
    easy:
      materialData: "WOOL:13"
      displayName: "&a&lEasy"
      lore:
      - ""
      - "&1Mines: &r5"
      - "&1Cost: &45"
      - "&1Reward: &a7"
      mines: 5
      # When an empty slot is revealed, surrounding slots are revealed automatically
      #   default: true
      automaticRevealing: true
      slot: 20
      cost: 5
      reward: 7
    normal:
      materialData: "WOOL:1"
      displayName: "&a&lNormal"
      lore:
      - ""
      - "&1Mines: &r8"
      - "&1Cost: &410"
      - "&1Reward: &a15"
      mines: 8
      cost: 10
      reward: 15
      slot: 29
    saveStats:
      materialData: "diamond_block"
      displayName: "&a&lHard"
      lore:
      - ""
      - "&1Mines: &r10"
      - "&cClimb up the &ltop list"
      - "&aGood luck!"
      - ""
      - "&1Cost: &450"
      - "&1Reward: &a75"
      - "&1Tokens: &a2"
      mines: 10
      big: false
      slot: 24
      cost: 50
      reward: 75
      # if true the best score of this button is saved
      saveStats: true
      tokens: 2
  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    saveStats:
      materialData: "diamond_block"
      displayName: "&a&lTop list"
      lore:
      - ""
      - "&aHard &1top list"
      slot: 33
      # inventory title of the top list (%player% and %game%)
      inventoryTitle: '              Top List'
      # Lore of the skulls in the inventory. Use %rank% for the rank and %time% for the time in 'mm:ss'
      skullLore:
      - ''
      - '&6Rank:&1 %rank%'
      - '&6Time:&1 %time%'


rules:
  # enable/disable sound
  playSounds: true


# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

# use "Material:data" or "ID:data"
materials:
  cover: "stained_glass_pane:7"
  flag: "SIGN"
  mine: "TNT"
  warning: "WOOL:1"

displaynames:
  cover: "&bCover"
  warning: "&cWarning"
  mine: "&4Mine"
  flag: "&1Flag"