# ----------------------------------------------------------------------------#
#                                                                             #
#                             Minesweeper config                              #
#                                                                             #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
langFile: "lang_en.yml"

gameBox:
  mainButton:
    # define the Material and data for the button (format: 'material:data')
    materialData: "TNT"
    # display name of the button
    displayName: "&1Minesweeper"
    # lore of the button
    lore:
    - ""
    - "&3Watch your step..."
  gameButtons:
    easy:
      materialData: "WOOL:13"
      displayName: "&aEasy"
      lore:
      - ""
      - "&1Mines: &r5"
      mines: 5
      slot: 11
      cost: 5
      reward: 7
    normal:
      materialData: "WOOL:1"
      displayName: "&6Normal"
      lore:
      - ""
      - "&1Mines: &r8"
      mines: 8
      cost: 10
      reward: 15
      slot: 20
    hard:
      materialData: "WOOL:14"
      displayName: "&cHard"
      lore:
      - ""
      - "&1Mines: &r11"
      mines: 11
      slot: 29
      cost: 15
      reward: 25
    saveStats:
      materialData: "diamond_block"
      displayName: "&c&lCompetition"
      lore:
      - ""
      - "&1Mines: &r11"
      - "Your best score will be saved"
      - "&aGood luck!"
      mines: 11
      slot: 24
      cost: 50
      reward: 75
      # if true the best score of this button is saved
      saveStats: true
  topListButtons:
    # use the same key as the game you want to display the top list for
    #   for that button 'saveStats' must be true (see above)
    saveStats:
      materialData: "diamond_block"
      displayName: "&cTop list"
      lore:
      - ""
      - "&1Show top list for '&cCompetition'"
      slot: 33


rules:
  # enable/disable sound
  playSounds: true
  # when you reveal an empty slot automatic revealing will uncover all attached empty slots until the first slot
  #   is not empty
  # change this to true if you DON'T want this option
  turnOffAutomaticRevealing: false


# requires vault and an economy plugin
#   to enable economy do not forget to enable it for GameBox too
economy:
  enabled: false

  
# you can use the section below to run commands if a player won a game
#   %player% will be replaced by the players name
wonCommands:
  enabled: false
  # commands to dispatch after a player won a game
  commands:
  - "tell %player% [Minesweeper] You won a diamond"
  - "give %player% diamond 1"


# use "Material:data" or "ID:data"
materials:
  cover: "160:7"
  flag: "SIGN"
  mine: "TNT"
  warning: "WOOL:1"

displaynames:
  cover: "&bCover"
  warning: "&cWarning"
  mine: "&4Boooom!"
  flag: "&1Flag"