name: Minesweeper
author: Nikl
main: me.nikl.minesweeper.Main
version: 1.5.1
commands:
  minesweeper:
    description: play the game
    usage: /minesweeper
    aliases: [mines, ms]
permissions:
  minesweeper.*:
    description: Gives all permissions
    children:
      minesweeper.admin: true
  minesweeper.admin:
    description: Gives all permissions
    default: op
    children:
      minesweeper.play: true
      minesweeper.reload: true
      minesweeper.bypass: true
  minesweeper.play:
    description: You are allowed to play
    default: true
  minesweeper.reload:
    description: You can reload the plugin
  minesweeper.bypass:
    description: Gives permission to not pay for games and not get rewards